name: Sysdig_Workflow
on: [push]

jobs:
  build-secure-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Scan image
      uses: sysdiglabs/scan-action@v3
      with:
        image-tag: "alpine/git:latest"
        sysdig-secure-token: ${{ secrets.SYSDIG_SECURE_TOKEN }}
